CREATE TABLE IF NOT EXISTS zodiac (
    id serial primary key,
    name text,
    img text,
    discript text
    
);

CREATE TABLE IF NOT EXISTS constellations (
    id serial primary key,
    name text,
    img text,
    discript text
);


-- INSERT INTO constellations (name, img, discript)
-- VALUES
-- ('Perseus', 'https://s-media-cache-ak0.pinimg.com/736x/a1/ee/ab/a1eeabb63352d4b8a69254b12c87b294--perseus-constellation-hang-a-picture.jpg', 'One of the brightest and most interesting stars in Perseus is Algol. The name Algol means demon star. Ancient skywatchers thought it was cursed because its brightness changes. Thats because Algol, which is about 75 light-years from Earth, is the most famous eclipsing binary star. Today, astronomers know that Algol is two separate stars. About once every three days, the fainter member of the pair passes in front of the brighter one, and Algol grows fainter.'),
-- ('Ursa Major', 'http://www.solarsystemquick.com/universe/ursa-major-mythology.jpg', 'Ursa Major is a large sprawling constellation, the third largest in fact. Its mainly known as the home of the Big Dipper, certainly the best known. The name, The Great Bear, seems to have been assigned to the constellation due to its northern latitudes. Only a prodigious bear could live in such a northerly climate.' ),
-- ('Pegasus', 'https://userscontent2.emaze.com/images/ee5a304d-b747-40a8-9f3f-b0285c8155e6/ac7ada19320d7462f69dc51c3d75114e.png', 'Pegasus is a conspicuous constellation, which includes the socalled Great Square of Pegasus. However, it must now share the northeast corner of the square with Andromeda. '),
-- ('Hercules', 'http://divinepageant.com/Hercules.jpg', 'While it’s the fifth largest constellation, it isnt very obvious. It is a sprawling constellation just to the west of Lyra'),
-- ('Cassiopeia', 'http://s1.thingpic.com/images/7Z/MYE6gaQTj14GLVewp4bgx4hP.jpeg', 'Cassiopeia, in Greek mythology, was a vain queen who often boasted about her beauty. She was the mother of Princess Andromeda, and in contrast to other figures being placed in the sky in honor, Cassiopeia was forced to the heavenly realms as punishment. As the story goes, she boasted that her beauty (or her daughters, depending on the story) was greater than that of the sea nymphs. This was quite an offense, and she was banned to the sky for all to gawk at. With its distinctive “W” shape formed by five bright stars, Cassiopeia is one of the most easily recognizable constellations in the night sky come fall and early winter. And because of that, the vain queen is one of the most oft-mentioned in pop culture and one of the earliest constellations that young children come to recognize in the sky. '),
-- ('Canis Major', 'http://www.secretsinplainsight.com/wp-content/uploads/CanisMajor.jpg', 'Canis Major represents the famed Greek dog Laelaps. There are a few origin stories, but the common theme is that he was so fast he was elevated to the skies by Zeus. Laelaps is also considered to be one of Orion’s hunting dogs, trailing behind him in the night sky in pursuit of Taurus the bull.Canis Major is notable because it contains the brightest star in the night sky, Sirius. Tradition notes that the first appearance of Canis Major in the dawn sky comes in late summer, ushering in the dog days of the season. In the night sky, it almost looks a stick figure, with Sirius at the head, and another bright star, Adhara, at its rear end.'),
-- ('Gemini', 'https://i.pinimg.com/236x/64/cb/f5/64cbf567ada9bee9bdfc5ea1c21435ba--honda-honda-gemini-constellation.jpg', 'Gemini represents the twins Castor and Pollux. While the twins’ mother was Leda, Castor’s father was the mortal king of Sparta, while Pollux’s father was King Zeus (He seduced Leda in the form of a swan, remember? These stories tend to all tie together!). When Castor was killed, the immortal Pollux begged Zeus to give Castor immortality, which he did by placing the brothers in the night sky for all time.'),
-- ('Orion', 'http://objective-news.ru/images/orion_1.gif', 'Orion is one of the largest and most recognizable of the constellations. It is viewable around the world, and has been mentioned by Homer, Virgil, and even the Bible, making it perhaps the most famous constellation. Orion was a massive, supernaturally gifted hunter who was the son of Poseidon. It was said he regularly hunted with Artemis (Goddess of the Hunt) on the island of Crete, and that he was killed either by her bow, or by the sting of the great scorpion who later became the constellation Scorpius.'),
-- ('Pisces', 'https://upload.wikimedia.org/wikipedia/commons/d/d9/Sidney_Hall_-_Urania%27s_Mirror_-_Pisces.jpg', 'The two fish of the sky represent Aphrodite and her son Eros, who turned themselves into fish and tied themselves together with rope in order to escape Typhon, the largest and most vile monster in all of Greek mythology. It’s not likely you’ll find Pisces in the middle of a city, as none of its individual stars are really worth noting or particularly bright. It forms a large “V” with the right fish forming a small “O” on the end, and the left fish forming a small triangle on the end (the image above doesn’t connect the dots in the upper left to make it a triangle).'),
-- ('Scorpius', 'https://s-media-cache-ak0.pinimg.com/originals/80/74/68/807468bdf86cbae8f4fcc6ee577b7a99.jpg', 'There are a variety of myths associated with the scorpion, almost all of them involving Orion the hunter. Orion once boasted that he could kill all the animals on the earth. He encountered the scorpion, and after a long, fierce fight, Orion was defeated. It was such a hard-fought battle that it caught the eye of Zeus, and the scorpion was raised to the night sky for all eternity.'),
-- ('Taurus', 'https://s-media-cache-ak0.pinimg.com/originals/3c/42/96/3c42968d8f5de313c1a453574d3db38d.jpg', 'Taurus is a large and prominent fixture in the winter sky. As one of the oldest recognized constellations, it has mythologies dating back to the early Bronze Age. There are several Greek myths involving Taurus. Two of them include Zeus, who either disguised himself as a bull or disguised his mistress as a bull in multiple escapades of infidelity. Another myth has the bull being the 7th labor of Hercules after the beast wreaked havoc in the countryside.'),
-- ('Ursa Minor', 'https://i.pinimg.com/736x/0f/10/73/0f107360a00e92476faa6c2c12088e25--the-little-bears-constellation-tattoos.jpg', 'Ursa Minor is famous for containing Polaris, the North Star. Many people erroneously think that the North Star is directly over their heads, but that’s only true at the North Pole. For most people in the Northern Hemisphere, it will be dipped into the night sky.Ursa Minor is better known as the Little Dipper. It’s visualized as a baby bear, with an unusually long tail. It can be distinguished from the Big Dipper not only by size, but by the emphasized curvature of the tail. When you’ve found the North Star at the end of the bear’s tail using the Big Dipper, it’s then easy to identify the rest of the constellation.'),
-- ('Columba', 'https://osr.org/wp-content/uploads/2017/02/columba.jpg', 'Columba constellation represents the dove. It was introduced by Petrus Plancius in the 16th century and originally named Columba Noachi, or Noah’s Dove, in reference to the dove that signalled to Noah that the Great Flood was receding.'),
-- ('Eridanus', 'https://heartstardotorg.files.wordpress.com/2016/04/eridanus.jpg?w=300&h=300', 'Eridanus is the ancient Greek name for the river Po in Italy. In mythology, Eridanus is usually associated with the story of Phaëton, the son of the Sun god Helios who begged his father to let him drive his chariiot across the sky. Helios agreed to this and Phaëton mounted the chariot. However, since he was an inexperienced driver, he soon lost control of the horses and the chariot plunged close to Earth, setting lands on fire and turning Libya into a desert. Zeus had to prevent further disaster and he struck the young man down with a thunderbolt. Phaëton fell into the river Eridanus and his father did not drive his chariot for days after his son’s death, leaving the world in darkness.'),
-- ('Cetus', 'https://s-media-cache-ak0.pinimg.com/736x/e8/a8/e4/e8a8e41bb33015ae5b65a4be33ae48b0--sea-monsters-johannes.jpg', 'Cetus constellation represents the sea monster sent by Poseidon to ravage King Cepheus’ land after his wife Cassiopeia had boasted that she was more beautiful than the Nereids.'),
-- ('Cygnus (Northern Cross)', 'https://i.pinimg.com/736x/62/6f/29/626f296930810d6611fca1e64e448fde--cygnus-constellation-constellations.jpg', 'Cygnus constellation is most commonly associated with the myth of Leda, the Spartan queen who gave birth to two sets of twins – the mortal Clytemnestra and Castor and the immortal Pollux and Helen – after being seduced by Zeus, who came to her in the form of a swan. The mortal children were fathered by Leda’s husband Tyndareus and the immortal ones by Zeus. Castor and Pollux are associated with Gemini constellation.'),
-- ('Draco', 'https://i.pinimg.com/736x/4e/19/6c/4e196c4c3708fc16b3ed8e968d4c7118--dragon-constellation-draco.jpg', 'Draco constellation represents the dragon Ladon, the mythical creature with a hundred heads that guarded the gardens of the Hesperides in Greek mythology. Heracles killed the dragon with his poisoned arrows as part of his Twelve Laborus. In Roman legend, Draco is associated with one of the Giant Titans who warred with Zeus and other Olympian gods for a decade. The Titan was killed by Minerva in battle and thrown into the sky, where it froze around the North Pole.'),
-- ('Libra', 'https://s-media-cache-ak0.pinimg.com/originals/8f/63/4d/8f634d9ae5f3d3115b740458fb0bdf35.jpg', 'The name Libra means “the weighing scales” in Latin, and the constellation represents the scales of justice held by Dike, the Greek goddess of justice, associated with Virgo constellation.'),
-- ('Corvus', 'https://s-media-cache-ak0.pinimg.com/736x/fc/96/8b/fc968b51b3fe0cc5586273f55d7917a4--military-diet-plans-constellations.jpg', 'Corvus is another Greek constellation. It represents the crow (or raven), the sacred bird of the god Apollo. In the myth, Apollo tells the raven to watch over his pregnant lover Coronis. After a while, Coronis loses interest in the god and falls in love with a human man. When the bird reports the affair to Apollo, the god becomes so angry that the raven did not stop the affair that he curses it, scorching the raven’s feathers and turning them black. (The bird had originally had white feathers.) Coronis’ son, the healer Asclepius, is represented by Ophiuchus constellation.'),
-- ('Lupus', 'https://s-media-cache-ak0.pinimg.com/736x/46/2e/c1/462ec1e3115ff18bf500817b4462a004--lupus-constellation-tattoo-lupus-tattoo.jpg', 'Lupus is a very old constellation, first catalogued by Ptolemy. It was not associated with the wolf until the Renaissance times. The Greeks called the constellation Therium, which means “wild animal,” and the Romans knew it as Bestia, the beast. The stars of Lupus used to be part of Centaurus constellation, and they represented an animal sacrificed by the centaur, who was holding it toward an altar, represented by Ara constellation.'),
-- ('Leo Minor', 'https://i.pinimg.com/236x/7b/32/bc/7b32bcd10ab079373ef844ba3ae377ea--leo-constellation-zodiac-constellations.jpg', 'Lupus is a very old constellation, first catalogued by Ptolemy. It was not associated with the wolf until the Renaissance times. The Greeks called the constellation Therium, which means “wild animal,” and the Romans knew it as Bestia, the beast. The stars of Lupus used to be part of Centaurus constellation, and they represented an animal sacrificed by the centaur, who was holding it toward an altar, represented by Ara constellation.'),
-- ('Leo', 'https://i.pinimg.com/236x/7b/32/bc/7b32bcd10ab079373ef844ba3ae377ea--leo-constellation-zodiac-constellations.jpg', 'Leo constellation is associated with the Nemean lion in Greek mythology, the beast killed by Heracles as part of his Twelve Labours.'),
-- ('Hydra', 'https://d1k5w7mbrh6vq5.cloudfront.net/images/cache/24/ec/9b/24ec9b37036e98d990be0e72f48fbb8d.jpg', 'The largest of the 88 constellations was named after the Lernaean Hydra, the monster from the myth of Heracles’ Twelve Labours. It is one of the Greek constellations, first documented by Ptolemy in the 2nd century.'),
-- ('Virgo', 'https://upload.wikimedia.org/wikipedia/commons/3/38/Sidney_Hall_-_Urania%27s_Mirror_-_Virgo.jpg', 'Virgo is one of the Greek constellations. It is associated with Dike, the Greek goddess of justice, holding the scales of justice represented by the neighbouring constellation Libra.');



-- INSERT INTO zodiac (name, img, discript)
-- VALUES 
-- ('Aries', 'https://www.horoscopedates.com/img/icon_aries.png', '21 March – 20 April That temperamental trait of individuals born with the Sun in the element of Fire is best seen in a young Aries. They are dynamic and full of energy, often forgetting to slow down, look into the past for some answers and learn from their experiences. Filled with enthusiasm and childish, an Aries is a true leader that will be able to spark your inner fire in no time. When active enough and focused on ways to focus their energy on their true goals, these people are representatives of Fire in its purest and controlled form.'),
-- ('Taurus', 'https://www.horoscopedates.com/img/icon_taurus.png', '21 April – 21 May Among the Earth signs, Taurus is the most stable because of its fixed quality. This can make individuals born with the Sun in it quite rigid, stubborn and unmovable, quite irritating to those marked by the element of Air. These individuals are wise, nurturing and reliable, with a mission to find physical satisfaction in this lifetime. They build a solid foundation for each relationship they commit to and won’t settle for any sort of material insecurity or fear. They need a strong basis to have some fun and enjoy their deeply calm and emotional nature. Seemingly clingy and tied up, they can be perfect companions in the long run.'),
-- ('Gemini', 'https://www.horoscopedates.com/img/icon_gemini.png', '22 May – 21 June The sign of Gemini is a mutable sign belonging to the element of Air. This makes it the least stable of all signs of the zodiac and people born with the Sun in Gemini can be hard to follow. They are always looking for something new and exciting, never having enough incredible experiences that will satisfy their craving for information and socializing. Their life seems like a search for something or someone to complete them and excite them enough so they can find peace. They need room to explore and show their intellectual and verbal magnificence daily.'),
-- ('Cancer	', 'https://www.horoscopedates.com/img/icon_cancer.png', '22 June – 22 July As a cardinal representative of the element of Water, the sign of Cancer is compassionate and caring on first impulse. Without overthinking, those born with the Sun in Cancer will be supportive and caring, with an open mind and heart for all human differences. Once they get hurt, these people close their hearts and become overprotective of those they still love, or their country and their home. Unaware of the lack of danger that lurks around the corner, they can get too attached to their home and even become afraid of leaving it or letting go of their memories.'),
-- ('Leo', 'https://www.horoscopedates.com/img/icon_leo.png', '23 July – 22 August Just like a middle child among the Fire signs, Leo craves to be the center of attention to everyone around. Belonging to the sign of fixed quality, they represent the personality that is proud and constant, with little room for change. This can make Leo representatives a tad difficult, for they have deep seeded, passionate respect for who they are and are often unaware of the requests of society and other people. Ruled by the Sun, Leo is passion and creativity in its most stable unchangeable form, giving balance to the Universe as we know it.'),
-- ('Virgo', 'https://www.horoscopedates.com/img/icon_virgo.png', '23 August – 23 September Virgo is a mutable Earth sign, representing soil that is not that tough and stiff as you always expect from Earth. In general, those born with the Sun in Virgo are less set in their ways than other Earth signs, but still have trouble remaining that flexible attitude when it comes to matters of the heart and their own emotional needs. They took the best from the earthly world though, as reliable and caring, while at the same time changeable enough to be fun to be with. They need to let emotions lead the way from time to time in order to achieve true inner state of satisfaction.'),
-- ('Libra', 'https://www.horoscopedates.com/img/icon_libra.png', '24 September – 23 October The sign of Libra is an Air sign with a Cardinal quality, making people born with the Sun in it potentially innovative and incredibly open for new things. Libras bring balance and harmony into our lives, much faster than their indecisiveness will let you believe. Their main problem is the fall of the Sun in their sign as they need to come to terms with their role of announcers of autumn, the season when all things are dying down. If they accept their personality in all its glory, they become joyful but calm, those few able to mend any relationship or conflict.'),
-- ('Scorpio	', 'https://www.horoscopedates.com/img/icon_scorpio.png', '24 October – 22 November Scorpio is a fixed Water sign. Slippery and dark, this is a sign of all dark places, dirty rivers that need to be cleansed and ancestors that brought us where we are today. Those born with this Sun sign are intense as they carry memories of their entire family tree on their skin, and have a task to overcome emotional challenges of those that are long gone. In their “underground activities”, digging through their subconscious, these individuals will find pools of greatest energy this planet has, like rivers of lava that burn their way through the stone.'),
-- ('Sagittarius', 'https://www.horoscopedates.com/img/icon_sagittarius.png', '23 November – 21 December The sign of Sagittarius is the Fire that is out of our reach, mutable in quality and really hard to grasp on. People born with their Sun in this sign are idealistic and always striving for more, aiming higher and higher, reaching for the sky. Representing the end of one season, a Sagittarius is the gentlest of all Fire signs, just like fire that goes out slowly, with all the work done and left behind. Philosophic and idealists, these individuals seem to be the closest to the element of Air and often pair with Air individuals for they seem to help them breathe.'),
-- ('Aquarius', 'https://www.horoscopedates.com/img/icon_aquarius.png', '21 January – 19 February Aquarius is a fixed Air sign that speaks of inevitability of change. It is a carrier of originality and ideas, one more related to the power of the mind. It speaks of our constant ability to be in touch with the Universe and the field of universal knowledge. People born with the Sun in this sign can be too erratic and unfocused, lost in their constant buzz. They will absorb more than they can metabolize and often turn to any form of humanitarian work just to handle the troubles of humanity in an acceptable manner, for they already see the world the way it should be.'),
-- ('Pisces', 'https://www.horoscopedates.com/img/icon_pisces.png', '20 February – 20 March The sign of Pisces is a mutable Water sign and represents the deepest oceans in their whole glory. Wide, lost, floating on the surface of the seas, those born with the Sun in Pisces often have trouble discovering their mission and their true path in life. This is a sign of hidden talents, those that aren’t approved by one’s family, and as such it can be the cause of suffering and feelings of incompetence. Spiritual and sensitive, these people are great missionaries with a cause to follow and a talent to share with the rest of the world.'),
-- ('Capricorn', 'https://www.horoscopedates.com/img/icon_capricorn.png', '22 December – 20 January The sign of Capricorn is the last Earth sign that opens us up to other worlds, everything that comes “after” and represents our strongest, inevitable faith. Cardinal quality in Capricorn individuals makes them strangely open for change, however closed up they might be for any sort of innovations along the way. Once they find a method that works, they will rarely change it but this doesn’t mean they won’t try many new things, often in secrecy out of fear of failure or making a mistake. Serious workers and career chasers, these individuals know how to reach point B from point A and are valuable as leaders and managers.');

